### ISSUE TITLE
How to use with Windows OneNote

### ISSUE THREAD

**Issue by rynoV** [BlueDrink9/vim_ahk#10]
I'm trying to use this script with the OneNote which is installed through the MicrosoftStore, which doesn't have the `onenote.exe` command. In order to run OneNote from the command line I have to run:
```
explorer.exe shell:appsFolder\Microsoft.Office.OneNote_8wekyb3d8bbwe!microsoft.onenoteim
```
How would I go about configuring this script to activate in that app? I realize this isn't really related to the script but any help will be greatly appreciated.

**Comment by rynoV** [comment]
I added OneNote by adding `ahk_exe ApplicationFrameHost.exe` to the `VimMenu > Settings > Application` list found by right clicking the executable's taskbar icon. I used Window Spy to find the name of the executable as recommended by a comment in `settings.ahk`.

**Comment by BlueDrink9** [comment]
Yup, that's pretty much the right thing to do.

I'd like to note that this version is very much a beta/development version, and is riddled with errors. For day-to-day use I'd suggest using the upstream version, rcmdnk/vim_ahk

For onenote-specific functionality, consider disabling onenote and using idvorkin/Vim-Keybindings-For-Onenote. You may need to do a similar trick to get the window recognised.
